% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2.5cm]{geometry}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{float}
\usepackage{setspace}
\onehalfspacing
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Taller 2 -- Curva CO en planes de muestreo},
  pdfauthor={Diego Fernando Muñoz Portela 2415620, Valery Rivera Lopez 2417038},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Taller 2 -- Curva CO en planes de muestreo}
\author{Diego Fernando Muñoz Portela 2415620, Valery Rivera Lopez
2417038}
\date{12 de marzo de 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Punto 1}\label{punto-1}

\subsection{Enunciado}\label{enunciado}

Suponga que usted tiene a su cargo la responsabilidad de recepción de
materia prima en una prestigiosa empresa de la región. En un acuerdo al
que se ha llegado con uno de sus proveedores, quien envía la materia
prima en lotes de 150 unidades, se estableció como un lote de muy buena
calidad aquel que presente un porcentaje de unidades defectuosas cercano
al 5\%.

Por otro lado el departamento de producción no está dispuesto a tolerar
ningún lote con más del 10\% de unidades defectuosas.

Como un lote se considera bueno si tiene menos del 5\%, se tomará un
tamaño de muestra \(n\) y se aceptará el lote si tiene menos del 5\% de
unidades defectuosas, por ejemplo:

\begin{itemize}
\tightlist
\item
  \((n=100, c=5)\)\\
\item
  \((n=80, c=4)\)\\
\item
  \((n=40, c=2)\)
\end{itemize}

\subsection{Preguntas}\label{preguntas}

\subsubsection{a. Evalué en cada caso los riesgos del productor y
consumidor.}\label{a.-evaluuxe9-en-cada-caso-los-riesgos-del-productor-y-consumidor.}

Dado que el tamaño del lote es pequeño (\(N=150\)) y la muestra (\(n\))
representa una parte significativa del lote, podemos suponer el uso de
una \textbf{Distribución Hipergeométrica}. Sin embargo, aplicaremos las
respectivas pruebas de distribucion en cada uno de los planes para
asegurarnos de usar la indicada para cada una de las probabilidades de
aceptación (\(P_a\)).

Para evaluar los riesgos en un lote de tamaño finito (\(N=150\)). La
probabilidad de aceptación (\(P_a\)) se calcula mediante la siguiente
sumatoria:

\[
P_a(p) = \sum_{x=0}^{c} \frac{\binom{D}{x} \binom{N-D}{n-x}}{\binom{N}{n}},
\]

\subsubsection{Definición de
variables:}\label{definiciuxf3n-de-variables}

\begin{itemize}
\item
  \(N\): Tamaño del lote (\(150\) unidades).
\item
  \(n\): Tamaño de la muestra tomada del lote.
\item
  \(c\): Número máximo de unidades defectuosas permitidas para aceptar
  el lote.
\item
  \(D\): Número total de unidades defectuosas existentes en el lote
  (\(D = p \cdot N\)).
\end{itemize}

\subsubsection{\texorpdfstring{Evaluación de Riesgos (\(\alpha\) y
\(\beta\))}{Evaluación de Riesgos (\textbackslash alpha y \textbackslash beta)}}\label{evaluaciuxf3n-de-riesgos-alpha-y-beta}

Basándonos en los niveles de calidad acordados, los riesgos se definen
de la siguiente manera:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Riesgo del Productor (}\(\alpha\)): Es la probabilidad de
  rechazar un lote que cumple con el Nivel de Calidad Aceptable
  (\textbf{AQL}). Se calcula cuando la proporción de defectos es
  \(p_0 = 0.05\).

  \[\alpha = 1 - P_a(p_0)\]
\item
  \textbf{Riesgo del Consumidor (}\(\beta\)): Es la probabilidad de
  aceptar un lote que tiene un Nivel de Calidad Límite (\textbf{LTPD}),
  es decir, mala calidad. Se calcula cuando la proporción de defectos es
  \(p_1 = 0.10\).

  \[\beta = P_a(p_1)\]
\end{enumerate}

Buscamos realizar los tres planes propuestos, todos con la relación
\(c/n = 0.05\).

\paragraph{\texorpdfstring{Plan 1: \(n = 100\),
\(c = 5\)}{Plan 1: n = 100, c = 5}}\label{plan-1-n-100-c-5}

\begin{verbatim}
## [1] "Hipergeométrica"
\end{verbatim}

\begin{verbatim}
## [1] 0.4654046
\end{verbatim}

\begin{verbatim}
## [1] 0.005796643
\end{verbatim}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/Plan 1-1} \end{center}

La curva característica de operación del Plan 1 presenta una caída
pronunciada a medida que aumenta la proporción defectuosa del lote. Esto
indica que el plan tiene una alta capacidad para discriminar entre lotes
buenos y malos. Cuando la proporción defectuosa se encuentra alrededor
del AQL (5\%), la probabilidad de aceptación todavía es considerable;
sin embargo, al acercarse al 10\%\textbf{,} la probabilidad disminuye de
manera \textbf{significativa, lo que} nos permite \textbf{tener} una
fuerte restricción hacia lotes de mala calidad. El riesgo del productor
obtenido es relativamente alto, lo que implica que existe una
probabilidad significativa de rechazar un lote que en realidad cumple
con el nivel aceptable de calidad. Por otro lado, el riesgo del
consumidor es extremadamente bajo, con un \(\beta_1\) del 0.57\%, lo que
significa que es muy poco probable que se acepte un lote con un nivel de
defectos inaceptable. Si se busca proteger principalmente al consumidor,
este será el plan adecuado ya que es el más estricto de los tres y el
que presenta mayor poder discriminante debido a su \textbf{elevado}
tamaño de muestra.

\paragraph{\texorpdfstring{Plan 2: \(n = 80\),
\(c = 4\)}{Plan 2: n = 80, c = 4}}\label{plan-2-n-80-c-4}

\begin{verbatim}
## [1] "Hipergeométrica"
\end{verbatim}

\begin{verbatim}
## [1] 0.4361659
\end{verbatim}

\begin{verbatim}
## [1] 0.02748011
\end{verbatim}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/PLAN 2-1} \end{center}

En el gráfico del Plan 2, la curva CO mantiene una tendencia decreciente
clara, aunque su \textbf{pendiente es ligeramente menos pronunciada}
(menos vertical) que la del plan anterior. Esto indica que el Plan 2
continúa diferenciando adecuadamente entre niveles de calidad aceptables
e inaceptables, pero con un menor \textbf{poder de discriminación}. El
riesgo del productor (\(\alpha_2\)) sigue siendo elevado, con un
\textbf{43.6\%} de probabilidad de rechazar un lote de buena calidad;
aunque este valor es ligeramente menor al del Plan 1, aún representa una
carga considerable para el proveedor. Por otro lado, el riesgo del
consumidor (\(\beta_2\)) \textbf{alcanza un 2.74\%}, lo que representa
un incremento de \textbf{2.18 puntos porcentuales} respecto al plan
anterior. Esta nueva curva CO refleja una situación intermedia: se busca
un mayor equilibrio entre la protección del productor y la del
consumidor, aunque el plan todavía mantiene un nivel de exigencia
importante debido a que el tamaño de muestra sigue siendo
representativo.

\paragraph{\texorpdfstring{Plan 3: \(n = 40\),
\(c = 2\)}{Plan 3: n = 40, c = 2}}\label{plan-3-n-40-c-2}

\begin{verbatim}
## [1] "Hipergeométrica"
\end{verbatim}

\begin{verbatim}
## [1] 0.3621672
\end{verbatim}

\begin{verbatim}
## [1] 0.1798492
\end{verbatim}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/PLAN 3-1} \end{center}

La curva correspondiente al Plan 3 es notablemente más plana y presenta
la pendiente menos pronunciada de los tres casos. Esto indica que este
plan tiene la \textbf{menor capacidad de discriminación} entre lotes
buenos y malos. A medida que aumenta la proporción defectuosa, la
probabilidad de aceptación disminuye de forma muy gradual, lo que
implica que, incluso con niveles de defectos inaceptables, existe una
probabilidad considerable de admitir el lote. El riesgo del productor
(\(\alpha_3\)) es el más bajo de los tres planes, situándose en un
\textbf{36.21\%}; esto significa que es el plan que menos castiga al
proveedor por lotes que cumplen con el AQL. Sin embargo, el
\textbf{riesgo del consumidor (}\(\beta_3\)) se dispara hasta un
17.98\%, lo que evidencia una vulnerabilidad crítica frente a lotes de
mala calidad. En consecuencia, este plan favorece claramente al
proveedor sobre el cliente, resultando el menos estricto de los tres
debido a su reducido tamaño de muestra

\subsubsection{b. ¿Se puede pensar entonces que un plan de muestreo con
la condición de proporcionalidad en AQL es equivalente, sin importar el
tamaño de
muestra?.}\label{b.-se-puede-pensar-entonces-que-un-plan-de-muestreo-con-la-condiciuxf3n-de-proporcionalidad-en-aql-es-equivalente-sin-importar-el-tamauxf1o-de-muestra.}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/Grafico_1b-1} \end{center}

\textbf{No.} A pesar de que en los tres planes propuestos se mantiene
una relación proporcional del 5\% entre el número de aceptación (\(c\))
y el tamaño de la muestra (\(n\)), los planes \textbf{no son
equivalentes} desde el punto de vista del control estadístico y la
gestión del riesgo.

La equivalencia de un plan de muestreo no está determinada por la
proporción \(c/n\), sino por la \textbf{pendiente de su Curva
Característica de Operación (CO)}, la cual depende directamente del
tamaño absoluto de la muestra (\(n\)). A continuación, se fundamenta
esta conclusión basándose en el comportamiento de los riesgos en cada
escenario:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Poder de Discriminación:} El Plan 1 (\(n=100\)) posee la curva
  más vertical, lo que le otorga un alto poder discriminante para
  separar lotes de buena calidad de los de mala calidad. A medida que
  \(n\) disminuye (Plan 2 y Plan 3), la curva se vuelve más ``suave'' o
  plana, perdiendo su capacidad de castigar los lotes que superan el
  nivel de defectos tolerado.
\item
  \textbf{Vulnerabilidad del Consumidor (Riesgo} \(\beta\)): Este es el
  factor que más evidencia la falta de equivalencia. Mientras que en el
  Plan 1 el riesgo del consumidor es extremadamente bajo
  (\(\beta_1 = 0.57\%\)), en el Plan 3, con la misma proporción del 5\%,
  el riesgo se dispara hasta un \textbf{17.98\%}. Esto significa que el
  cliente tiene casi \textbf{30 veces más probabilidad} de aceptar un
  lote malo en el Plan 3 que en el Plan 1.
\item
  \textbf{Relación de Riesgos:} * Los planes con muestras grandes (Plan
  1) son \textbf{estrictos}: protegen mucho al consumidor pero aumentan
  el riesgo del productor (\(\alpha\)), ya que el rigor del plan puede
  rechazar lotes que están apenas en el límite del AQL.

  \begin{itemize}
  \tightlist
  \item
    Los planes con muestras pequeñas (Plan 3) son \textbf{indulgentes}:
    favorecen al productor al reducir el riesgo de rechazo injusto, pero
    dejan al consumidor con una protección insuficiente.
  \end{itemize}
\end{enumerate}

\textbf{Conclusión final:}

Mantener la proporcionalidad solo asegura una relación matemática
superficial. En la práctica, reducir el tamaño de la muestra debilita la
protección del sistema de calidad. Por lo tanto, un plan de muestreo
debe elegirse basándose en el \textbf{balance de riesgos (}\(\alpha\) y
\(\beta\)) que la empresa esté dispuesta a asumir, y no simplemente en
una regla de tres simple sobre el nivel de aceptación.

\section{Punto 2}\label{punto-2}

\subsection{Enunciado}\label{enunciado-1}

Construya una Curva característica de operación para un plan de muestreo
simple en el cual el tamaño del lote es de 100 unidades, tamaño de
muestra 50, y numero de aceptación 2. Utilice las tres distribuciones de
probabilidad.

\subsection{Preguntas}\label{preguntas-1}

\subsubsection{a. ¿Se presentan discrepancias entre las
curvas?}\label{a.-se-presentan-discrepancias-entre-las-curvas}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/plan23-1} \end{center}

La distribución hipergeométrica (verde) presenta un comportamiento
escalonado debido a su naturaleza discreta y al tamaño finito del lote.
Dado que N=100, los cambios en los numeros de defectuosos ocurren en
valores enteros, generando variaciones abruptas en la probabilidad de
aceptación.

Además, esta distribución describe con mayor precisión el riesgo real
del plan de muestreo, ya que considera el agotamiento de la población
durante el muestreo (sin reemplazo).

Por el contrario, las aproximaciones binomial y Poisson asumen
poblaciones infinitas o muestreo con reemplazo, lo que genera ligeras
sobreestimaciones en la probabilidad de aceptación.

\subsubsection{b. ¿Que sucede si el tamaño del lote es de 2000
unidades?}\label{b.-que-sucede-si-el-tamauxf1o-del-lote-es-de-2000-unidades}

\begin{center}\includegraphics{RMK_FINAL---copia_files/figure-latex/plan24-1} \end{center}

La distribución hipergeométrica ya no presenta un comportamiento
escalonado visible, debido a que el tamaño del lote es grande N = 2000.
En este caso, los cambios en el número de defectuosos afectan muy poco
la probabilidad de aceptación, haciendo que la curva sea prácticamente
continua.

Además, dado que la fracción de muestreo es pequeña, el efecto de
agotamiento de la población es mínimo. Por esta razón, las
distribuciones binomial y Poisson se aproximan muy bien a la
hipergeométrica.

Se observa que las tres curvas prácticamente coinciden, lo que indica
que para lotes grandes, las aproximaciones binomial y Poisson describen
adecuadamente el comportamiento real del plan de muestreo.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
