---
title: "Taller 3 – plan de muestreo estándar"
author: "Diego Fernando Muñoz Portela 2415620, Valery Rivera Lopez 2417038, Alejandro Barros Rayo 2415837 "
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
fontsize: 12pt
geometry: margin=2.5cm
header-includes:
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{booktabs}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{setspace}
  - \onehalfspacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center",
  fig.width = 6,
  fig.height = 4
)
```

```{r 1, include=FALSE}
library(AQLSchemes) 

#Plan simple con nivel de inspección Normal
planS_1<-AASingle('Normal')
planS_1
planS_2<-AASingle('Normal')
planS_2
planS_3<-AASingle('Normal')
planS_3

#Plan simple con nivel de inspección Estricto
planE_1<-AASingle('Tightened')
planE_1
planE_2<-AASingle('Tightened')
planE_2
planE_3<-AASingle('Tightened')
planE_3

#Plan simple con nivel de inspección Reducido
planr_1<-AASingle('Reduced')
planr_1
planr_2<-AASingle('Reduced')
planr_2
planr_3<-AASingle('Reduced')
planr_3


```